title: 2021 ERA Workshop
logo: /assets/img/logo.png
description: 2021 Emerging Researchers in Artificial Life Workshop (<a href="http://2021.alife.org/">@ ALife 2021</a>)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
